name: personal_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animations: ^2.0.10
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
