// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOGT6zXNW9HRN-6vEZRNEU4tiYDTjeB-I',
    appId: '1:302147624712:web:6cfd920566f43d10db16bd',
    messagingSenderId: '302147624712',
    projectId: 'personal-website-49439',
    authDomain: 'personal-website-49439.firebaseapp.com',
    storageBucket: 'personal-website-49439.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Qc7vNdNzj6wvgORk1V17FRwgu7G8LW4',
    appId: '1:302147624712:android:e61ca399707df205db16bd',
    messagingSenderId: '302147624712',
    projectId: 'personal-website-49439',
    storageBucket: 'personal-website-49439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAPw6MsUnaGWTwHazZ9WnVAuCeFiK2DKo',
    appId: '1:302147624712:ios:44a1d9900d505a2cdb16bd',
    messagingSenderId: '302147624712',
    projectId: 'personal-website-49439',
    storageBucket: 'personal-website-49439.appspot.com',
    iosBundleId: 'com.example.personalWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAPw6MsUnaGWTwHazZ9WnVAuCeFiK2DKo',
    appId: '1:302147624712:ios:d4a7aab920138e51db16bd',
    messagingSenderId: '302147624712',
    projectId: 'personal-website-49439',
    storageBucket: 'personal-website-49439.appspot.com',
    iosBundleId: 'com.example.personalWebsite.RunnerTests',
  );
}
